# Stage 1: Builder
FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --target=/app/install \
 && rm -rf /root/.cache

COPY . .

# Stage 2: Distroless Runtime
FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=builder /app /app

ENV PYTHONPATH=/app/install

EXPOSE 8000

CMD ["main.py"]